#!/bin/sh -x

Rscript packages/nimble/inst/tests/test-allocation.R
Rscript packages/nimble/inst/tests/test-checkDSL.R
Rscript packages/nimble/inst/tests/test-compareMCMCs.R
Rscript packages/nimble/inst/tests/test-copy.R
Rscript packages/nimble/inst/tests/test-coreR.R
Rscript packages/nimble/inst/tests/test-declare.R
Rscript packages/nimble/inst/tests/test-distributions.R
Rscript packages/nimble/inst/tests/test-dsl_dists.R
Rscript packages/nimble/inst/tests/test-errors.R
Rscript packages/nimble/inst/tests/test-filtering.R
Rscript packages/nimble/inst/tests/test-getBound.R
Rscript packages/nimble/inst/tests/test-getDependencies.R
Rscript packages/nimble/inst/tests/test-getDistributionInfo.R
Rscript packages/nimble/inst/tests/test-getParam.R
Rscript packages/nimble/inst/tests/test-math.R
Rscript packages/nimble/inst/tests/test-mcem.R
Rscript packages/nimble/inst/tests/test-mcmc.R
Rscript packages/nimble/inst/tests/test-misc.R
Rscript packages/nimble/inst/tests/test-modelValuesInterface.R
Rscript packages/nimble/inst/tests/test-models.R
Rscript packages/nimble/inst/tests/test-nimbleFunctionInterfaces.R
Rscript packages/nimble/inst/tests/test-nimbleList.R
Rscript packages/nimble/inst/tests/test-nimbleList_RCfun.R
Rscript packages/nimble/inst/tests/test-numericTypes.R
Rscript packages/nimble/inst/tests/test-optim.R
Rscript packages/nimble/inst/tests/test-setData.R
Rscript packages/nimble/inst/tests/test-size.R
Rscript packages/nimble/inst/tests/test-trunc.R
Rscript packages/nimble/inst/tests/test-types.R
Rscript packages/nimble/inst/tests/test-user.R
