--- 
title: "NIMBLE User Manual"
author: "NIMBLE Development Team"
date: "Version 0.6-12"
site: bookdown::bookdown_site
output: bookdown::gitbook
documentclass: book
bibliography: [UserManualRefs.bib]
biblio-style: apalike
link-citations: yes
github-repo: rstudio/bookdown-demo
description: "This is a minimal example of using the bookdown package to write a book. The output format for this example is bookdown::gitbook."
---


```{r echo=FALSE, include=FALSE}
library(knitr)
library(nimble)
library(methods)
opts_chunk$set(eval = TRUE, message = FALSE) ## turned off message() output
nimbleOptions(MCMCprogressBar = FALSE)
runMCEMs <- TRUE
nimbleVersion="0.6-12"
```
<!---
rmd_files: ["index.Rmd", "chapter_WelcomeToNimble.Rmd", "chapter_LightningIntroduction.Rmd", "chapter_MoreIntroduction.Rmd", "chapter_InstallingNimble.Rmd", "chapter_WritingModels.Rmd", "chapter_BuildingModels.Rmd", "chapter_MCMC.Rmd", "chapter_OtherAlgorithms.Rmd", "chapter_Spatial.Rmd", "chapter_BNP.Rmd", "chapter_ProgrammingOverview.Rmd", "chapter_RCfunctions.Rmd", "chapter_UserDefined.Rmd", "chapter_UsingModels.Rmd", "chapter_DataStructures.Rmd", "chapter_WritingNimbleFunctions.Rmd"]
-->

```{r echo=FALSE, include=FALSE, eval=FALSE}
## for creating combined tables for functions in Writing Models and NF programming
system("cat functionTableLong.md eigenSvdTableMatrixElements.md > tmp.md")
```
```{r, child = 'tmp.md', eval=FALSE}
```
```{r echo=FALSE, include=FALSE, eval=FALSE}
system("rm -rf tmp.md")
```


