
if(!exists('.NimbleUseRegistration') || !.NimbleUseRegistration) {
   resizeManyModelVarAccessor = 'resizeManyModelVarAccessor'
   resizeManyModelValuesAccessor = 'resizeManyModelValuesAccessor'
   getAvailableNames = 'getAvailableNames'
   getModelObjectPtr = 'getModelObjectPtr'
   getModelValuesMemberElement = 'getModelValuesMemberElement'
   getNRow = 'getNRow'
   addBlankModelValueRows = 'addBlankModelValueRows'
   copyModelValuesElements = 'copyModelValuesElements'
   setMVElement = 'setMVElement'
   getMVElement = 'getMVElement'
   R_setPtrVectorOfPtrs = 'setPtrVectorOfPtrs'
   R_setOnePtrVectorOfPtrs = 'setOnePtrVectorOfPtrs'
   R_setDoublePtrFromSinglePtr = 'setDoublePtrFromSinglePtr'
  ## R_setSinglePtrFromSinglePtr = 'setSinglePtrFromSinglePtr'
   C_dwish_chol = 'C_dwish_chol'
   C_rwish_chol = 'C_rwish_chol'
   C_ddirch = 'C_ddirch'
   C_rdirch = 'C_rdirch'
   C_dmulti = 'C_dmulti'
   C_rmulti = 'C_rmulti'
   C_dcat = 'C_dcat'
   C_rcat = 'C_rcat'
   C_dt_nonstandard = 'C_dt_nonstandard'
   C_rt_nonstandard = 'C_rt_nonstandard'
   C_dmnorm_chol = 'C_dmnorm_chol'
   C_rmnorm_chol = 'C_rmnorm_chol'
   makeNumericList = 'makeNumericList'
   newModelValues = 'newModelValues'
   testRows = 'testRows'
   }

