\documentclass[12pt,oneside]{book}
\usepackage{geometry}

\geometry{tmargin = 1in, bmargin = 1in, lmargin = 1in, rmargin = 1in}

\begin{document}

<<chunk-LIinit, echo = FALSE>>=
## source the code
read_chunk(file.path('writingModels_chunks.R'))  # one can put code chunks here if one wants
@ 

Here is the figure:

<<linearRegressionGraph, fig.height=10, fig.width=20, echo=FALSE, message=FALSE, fig.cap="Graph of a linear regression model">>=
@ 

Here is text after the figure.

\end{document}
