#!/usr/bin/env Rscript

# This script is used to generate some C++ files in nimble/inst.
# You should run this script if you make changes to the internal representation
# of nimbleLists.
#
# Directions:
# 1. Install clang-format.
# 2. Temporarily set `predefined = FALSE` in the definitions of `optimResultNimbleList` and `optimControlNimbleList`.
# 3. Run this script.

library(nimble)

# This finds the latest generated .h and .cpp files.
findGeneratedSources <- function() {
    root <- file.path(tempdir(), 'nimble_generatedCode')
    files <- file.info(list.files(root, full.names = TRUE))
    files <- files[order(files$mtime, decreasing = TRUE),]
    paths <- rownames(files)
    paths_h <- paths[grep('\\bP_\\w+\\.h$', paths)]
    paths_cpp <- paths[grep('\\bP_\\w+\\.cpp$', paths)]
    ret <- system2('clang-format', list('-i', paths_h[1], paths_cpp[1]))
    if(ret != 0) stop('Please install clang-format and try again')
    return(list(.h = paths_h[1], .cpp = paths_cpp[1]))
}

readRelevantLines <- function(filename) {
    con <- file(filename, open = 'r')
    lines = readLines(con)
    close(con)

    # Parse file using a little state machine.
    step <- 'HEADER'
    for(i in seq_along(lines)) {
        if (step == 'HEADER') {
            if (length(grep('REMOVE_THIS_CODE', lines[i])) == 0) {
                beginBody <- i
                step <- 'BODY'
            }
        } else if (step == 'BODY') {
            if (length(grep('REMOVE_THIS_CODE', lines[i])) == 1) {
                endBody <- i - 1
                break
            }
        }
    }
    return(lines[beginBody:endBody])
}

writeFile <- function(filename, lines) {
    cat('Generating', filename, '\n')
    con <- file(filename, open = 'w')
    writeLines(lines, con)
    close(con)
    ret <- system2('clang-format', c('-i', "-style='{BasedOnStyle: Google, IndentWidth: 4}'", filename))
    if(ret != 0) stop('Please install clang-format and try again')
}

main <- function() {
    # Generate code with some unwanted garbage.
    nimFun <- nimbleFunction(
        name = 'REMOVE_THIS_CODE',
        setup = TRUE,
        run = function() {
            return(optimResultNimbleList$new())
            returnType(optimResultNimbleList())
        },
        methods = list(
            control = function() {
                return(optimControlNimbleList$new())
                returnType(optimControlNimbleList())
            }
        )
    )()

    # Compilation will fail because we have duplicate definitions, but that's ok.    
    tryCatch(compileNimble(nimFun), error = function(e){})

    # Read the relevant parts of both files.
    files <- findGeneratedSources()
    lines_h <- readRelevantLines(files$.h)
    lines_cpp <- readRelevantLines(files$.cpp)

    # Patch header to avoid #including nimOptim.h.
    badIncludeLine <- grep('#include <nimble/nimOptim.h>', lines_h)[1]
    lines_h <- lines_h[-badIncludeLine]

    # Write the header.
    provenance <- c(
        '// DO NOT EDIT BY HAND.',
        '// This file was automatically generated by nimble/packages/generateStaticCode.R',
        ''
    )
    writeFile(
        file.path('nimble', 'inst', 'include', 'nimble', 'optimTypes.h'),
        c(
            provenance,
            '#ifndef __NIMBLE_OPTIMTYPES_H',
            '#define __NIMBLE_OPTIMTYPES_H',
            '',
            '#include <nimble/smartPtrs.h>',
            lines_h,
            '#endif  // __NIMBLE_OPTIMTYPES_H'
        )
    )
    writeFile(
        file.path('nimble', 'inst', 'CppCode', 'optimTypes.cpp'),
        c(
            provenance,
            '#include <nimble/optimTypes.h>',
            lines_cpp
        )
    )
}

main()
