#!/usr/bin/Rscript

# this script creates the Rd files from the roxygen info in the R files
# and creates the NAMESPACE file

library(roxygen2)
library(methods)

### 1. Create Rd files and first-pass NAMESPACE

if(!file.exists(file.path('nimble','R','config.R')))
    stop("You need a nimble/R/config.R file, but it must NOT be in the repository; you can probably do the following to create config.R from nimble/packages: 'make configure; cd nimble; ./configure'.")

## As of 2022-02-19, if we don't keep NAMESPACE, the initial build done by roxygenize fails. And roxygen2 won't overwrite NAMESPACE without the "generated by roxgen2 preamble".
## out <- file.remove(file.path('nimble', 'NAMESPACE'))  ## roxygen2 doesn't want to overwrite if file not created by roxygen2; assignment to out prevents printing of TRUE/FALSE
tmp <- readLines(file.path('nimble','NAMESPACE'))
tmp <- c('# Generated by roxygen2: do not edit by hand', tmp)
writeLines(tmp, file.path('nimble','NAMESPACE'))
roxygenize('nimble', c('namespace','rd'))


### 2. Create nimble-internals.Rd as CRAN-required documentation for internal functions that need to be exported

## build/install package so can get list of all package functions
system("R CMD build nimble")
nimble_version <- system("grep 'Version:' nimble/DESCRIPTION | cut -d' ' -f2", intern = TRUE)
system(paste0("R CMD INSTALL nimble_", nimble_version, ".tar.gz"))
library(nimble)
funs <- ls('package:nimble')

documentedFuns <- list.files(file.path("nimble", "man"), pattern = "*Rd$")
documentedFuns <- sub(".Rd$", "", documentedFuns)

## pull in all the @aliases and @names in the Rd files
cur <- getwd()
setwd(file.path("nimble", "man"))
tmp <- readLines(pipe("cat *Rd"))
aliases <- tmp[grep("^(\\\\name|\\\\alias)", tmp)]
aliases <- gsub("^(\\\\name|\\\\alias)\\{", "", aliases)
aliases <- gsub("\\}", "", aliases)
aliases <- unique(aliases)

setwd(cur)

## combination of file names and @aliases and @names, though all file names are probably in @name or @alias...
documentedFuns <- unique(c(documentedFuns, aliases))
undocFuns <- funs[!funs %in% documentedFuns]
# make sure to have fooClass-Class documented in nimble-internal to pass R CMD check
undocClasses <- undocFuns[grep("Class$", undocFuns)]

undocClasses <- paste0(undocClasses, "-Class", sep = '')

## need the following additional exports that need to be doc'ed by CRAN rules

## need to document all S4 methods
explicitUndocFuns <- c("[,numberedModelValuesAccessors-method",
                       "[<-,numberedModelValuesAccessors-method",
                       "[,numberedObjects-method",
                       "[<-,numberedObjects-method",
                       "[[,CNumericList-method",
                       "[[<-,CNumericList-method",
                       "[[,RNumericList-method",
                       "[[<-,RNumericList-method",
                       "[[,nimPointerList-method",
                       "[[<-,nimPointerList-method",
                       "[[<-,nimbleFunctionList-method",
                       "[,distributionsClass-method",
                       "[[,distributionsClass-method",
                       "[[,conjugacyRelationshipsClass-method",
                       "dsqrtinvgamma",
                       "rsqrtinvgamma",
                       "is.Cmodel",
                       "is.Cnf",
                       "is.Rmodel",
                       "is.model",
                       "nf_preProcessMemberDataObject",
                       "samplesSummary",
                       "messageIfVerbose")

additionalExports <- c("calc_dmnormConjugacyContributions",
                       "calc_dmnormAltParams",
                       "calc_dwishAltParams",
                       "calc_dcatConjugacyContributions",
                       "CAR_calcM",
                       "CAR_calcC",
                       "CAR_calcCmatrix",
                       "CAR_calcEVs2",
                       "CAR_calcEVs3",
                       "getNodeFunctionIndexedInfo",
                       "singleModelValuesAccess",
                       "getNimbleProject",
                       "cc_getNodesInExpr",
                       "calcAdaptationFactor",
                       "is.nfGenerator",
                       "mcmc_createModelObject",
                       "nimbleInternalFunctions",
                       "nimbleUserNamespace",
                       "buildAGHQuad",
                       "buildOneAGHQuad",
                       "buildOneAGHQuad1D")

## Not clear why we need this but this is not being put in NAMESPACE otherwise.
## It can't be in 'additionalExports' as it does have documentation.
additionalExportsNotInternal <- c('nimbleFunctionList')

internals <- c(undocClasses, explicitUndocFuns, additionalExports)

text <- rep("", length(internals))
for(i in seq_along(internals)) 
  text[i] <- paste0("\\alias{", internals[i], "}")

internalDesc <- "\\description{\nFunctions and classes used internally in NIMBLE and not expected to be called directly by users. Some functions and classes not intended for direct use are documented and/or exported because they are used within Reference Class methods for classes programmatically generated by NIMBLE.\n}\n\\author{NIMBLE Development Team}"

text <- c("\\name{nimble-internal}", "\\title{Functions and Classes Internal to NIMBLE}",
          text, internalDesc)

cat(paste(text, collapse = "\n"), file = file.path("nimble", "man", "nimble-internal.Rd"))

### 3. Create nimble-math.Rd as documentation for various math functions we don't want to write individual documentation for given similarity to BUGS or base R functions

mathFuns <- c('besselK',
              'cloglog',
              'cube',
              'expit',
              'icloglog',
              'ilogit',
              'inprod',
              'inverse',
              'iprobit',
              'logdet',
              'logfact',
              'loggam',
              'logit',
              'nimEquals',
              'nimRound',
              'nimStep',
              'nimSwitch',
              'phi',
              'pow',
              'probit')

text <- rep("", length(mathFuns))
for(i in seq_along(mathFuns)) 
  text[i] <- paste0("\\alias{", mathFuns[i], "}")

internalDesc <- "\\description{\nMathematical functions for use in BUGS code and in nimbleFunction programming (i.e., nimbleFunction run code). See Chapter 5 of the User Manual for more details.\n}\n\\author{NIMBLE Development Team}"

text <- c("\\name{nimble-math}", "\\title{Mathematical functions for BUGS and nimbleFunction programming}", text, internalDesc)

cat(paste(text, collapse = "\n"), file = file.path("nimble", "man", "nimble-math.Rd"))

### 4. Create final NAMESPACE file, which is careful about what is exported

imports <- c("methods", "igraph")
imports <- paste("import(", imports, ")", sep = '', collapse = "\n")

importFroms <- c("coda, effectiveSize, as.mcmc, as.mcmc.list",
                 "R6, R6Class",
                 "grDevices, dev.off, jpeg",
                 "graphics, lines, plot, text",
                 "stats, aggregate, ar, lm, optim, pnorm, qnorm, residuals, runif, sd, var, median, quantile",
                 "utils, head",
                 "parallel, mclapply",
                 "pracma, hessian",
                 "numDeriv, genD, grad, jacobian"
                 )
##                 "R2WinBUGS, bugs",
##                 "rjags, jags.model",
##                 "rjags, coda.samples",
##                 "rstan, stan_model",
##                 "rstan, sampling")

importFroms <- paste("importFrom(", importFroms, ")", sep = "", collapse = "\n") 

dynLibLine <- "useDynLib(nimble, .registration = TRUE)"

S3methods <- c("as.matrix, CmodelValues",
               "as.matrix, modelValuesBaseClass",
	       "as.list, CmodelValues",
	       "as.list, modelValuesBaseClass",
               "length, nimPointerList")

S3methods <- paste("S3method(", S3methods, ")", sep = "", collapse = "\n")

exportText <- readLines(file.path('nimble','NAMESPACE'))
## remove extra roxygen lines:
exportText <- exportText[grep("^#", exportText, invert = TRUE)]
exportText <- exportText[grep("^$", exportText, invert = TRUE)]

## fix incorrect S3method(is.na,vec), S3Method(is.nan,vec) produced by roxygen2
exportText[exportText == "S3method(is.na,vec)"] <- "export(is.na.vec)"
exportText[exportText == "S3method(is.nan,vec)"] <- "export(is.nan.vec)"

additionalExports <- c(additionalExports, additionalExportsNotInternal, 'nimbleType')  # nimbleType needed it is being exported only as a class as it is officially a refClass not a function
exportTextAdd <- paste0("export(", additionalExports, ")")
exportText <- c(exportTextAdd, exportText)

cat(
    paste(imports, importFroms, dynLibLine, S3methods, collapse = '\n', sep = '\n'),
    '\n',
    paste0(exportText, collapse = '\n'),
    '\n',
    sep = '', file = file.path("nimble", "NAMESPACE"))


## Not sure why this is getting created - I think it is because
## of new roxygen package version. Need to remove or R CMD check complains.
soFile <- file.path('nimble','inst','CppCode', 'libnimble.so')
if(file.exists(soFile))
    file.remove(soFile)
